// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecjnnsfrrtkogwiqyley.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjam5uc2ZycnRrb2d3aXF5bGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTM2OTgsImV4cCI6MjA2MTU2OTY5OH0.1tQs4Uu4r4WcUYZKNjAhaxRcCA8dyO7wr26pX_mN7zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);